### ISSUE TITLE
element 扩展

### ISSUE THREAD

**Issue by ZhongHongLi** [guokangf/vue-element-utils#3]
你好这个可以在源码中用吗？ 就是element

**Comment by Ray-56** [comment]
可以的，就是给 Element-ui 做的拓展指令

**Comment by Ray-56** [comment]
可以直接下 npm 包使用，使用方法都写了，有啥问题，提 Issue 我会及时反馈的

**Comment by ZhongHongLi** [comment]
好的。謝謝




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "56"<notifications@github.com&gt;; 
发送时间: 2020年10月27日(星期二) 下午3:27
收件人: "Ray-56/vue-element-utils"<vue-element-utils@noreply.github.com&gt;; 
抄送: "遗忘的小丑"<www.fz948605929@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Ray-56/vue-element-utils] element 扩展 (#3)





 
可以直接下 npm 包使用，使用方法都写了，有啥问题，提 Issue 我会及时反馈的

**Comment by Ray-56** [comment]
如果好用的话 可以给个 star 😁

**Comment by ZhongHongLi** [comment]
好的。我現在去給。但是我後面換了其他的方法，你這個沒支持限制区域。还有一个就是关闭了还会在上次的位置



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "56"<notifications@github.com&gt;; 
发送时间: 2020年10月27日(星期二) 下午3:31
收件人: "Ray-56/vue-element-utils"<vue-element-utils@noreply.github.com&gt;; 
抄送: "遗忘的小丑"<www.fz948605929@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Ray-56/vue-element-utils] element 扩展 (#3)





 
如果好用的话 可以给个 star 😁

**Comment by Ray-56** [comment]
恩恩，是的，完了补充一下

**Comment by ZhongHongLi** [comment]
我给你star了。谢谢作者热情的回复。感谢了，如果后面补充了肯定会有很多人用




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "56"<notifications@github.com&gt;; 
发送时间: 2020年10月27日(星期二) 下午3:34
收件人: "Ray-56/vue-element-utils"<vue-element-utils@noreply.github.com&gt;; 
抄送: "遗忘的小丑"<www.fz948605929@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Ray-56/vue-element-utils] element 扩展 (#3)





 
恩恩，是的，完了补充一下

**Comment by Ray-56** [comment]
边界问题已经补充了，后续可以推荐朋友用用，蟹蟹哈

**Comment by ZhongHongLi** [comment]
哈哈，点个赞



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "56"<notifications@github.com&gt;; 
发送时间: 2020年10月30日(星期五) 下午2:56
收件人: "Ray-56/vue-element-utils"<vue-element-utils@noreply.github.com&gt;; 
抄送: "遗忘的小丑"<www.fz948605929@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Ray-56/vue-element-utils] element 扩展 (#3)





 
边界问题已经补充了，后续可以推荐朋友用用，蟹蟹哈
